name: Issues - Triage 🚦
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  put-issue-to-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Send issues to triage
        uses: andymckay/labeler@1.0
        with:
          labels: "state/triage 🚦"
          repo-token: ${{ secrets.GITHUB_TOKEN }}