name: Issues - Stolen 🦴
on:
  schedule:
  - cron: "42 8,23 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 12
          days-before-pr-stale: -1
          days-before-pr-close: -1
          
          stale-issue-label: "state/slote 🦴,stale/stale 🦴"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          
          close-issue-label: "state/slote 🦴,stale/dead 💀"
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."

          exempt-issue-labels: "state/confirmed 💜,slate/lock 🔒"
          exempt-pr-labels: "state/confirmed 💜,slate/lock 🔒"
          exempt-all-milestones: true
          exempt-assignees: "42Atomys"

          remove-stale-when-updated: true
          labels-to-add-when-unstale: "stale/unstale 🍖"
          labels-to-remove-when-unstale: "stale/stale 🦴,stale/dead 💀,state/slote 🦴"

          enable-statistics: true