name: K6 🛠️
on: 
  pull_request:
    types:
    - ready_for_review
  push:
    branches:
    - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  k6-load-script:
    name: "K6 Load test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: [ '1.18' ]
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.goVersion }}
        check-latest: true
    - name: Install k6
      run: |
        curl https://github.com/grafana/k6/releases/download/v0.39.0/k6-v0.39.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
    - name: Start application and run K6
      continue-on-error: true
      run: |
        go run main.go serve --config tests/webhooks.tests.yml >/dev/null 2>&1 &
        sleep 20
        ./k6 run tests/k6-load-script.js