name: Tests 🛠️
on: 
  pull_request:
  push:
    branches:
    - main
    paths:
    - '**/*.go'
    - '**/*.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  applications-test-units:
    name: "GoLang test units"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVersion: [ '1.17', '1.18' ]
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Start Redis
      uses: supercharge/redis-github-action@1.5.0
      with:
        redis-version: 6
    - name: Setup RabbitMQ
      uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3.8.2-management-alpine'
        host port: 5672
        rabbitmq user: 'user'
        rabbitmq password: 'password'
    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
        postgresql db: webhook_db
        postgresql user: webhook
        postgresql password: test
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.goVersion }}
        check-latest: true
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        version: latest
    - name: Run Unit tests
      run: |
        go test ./... -coverprofile coverage.out -covermode count
        go tool cover -func coverage.out
    - name: Quality Gate - Test coverage shall be above threshold
      env:
          TESTCOVERAGE_THRESHOLD: 90
      run: |
        echo "Quality Gate: checking test coverage is above threshold ..."
        echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
        totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "Current test coverage : $totalCoverage %"
        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
            echo "OK"
        else
            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
            echo "Failed"
            exit 1
        fi
    - uses: codecov/codecov-action@v3
    - name: Run Go Build
      run: |
        go build -o /tmp/applications-test-units